version: 3.0.{build}

skip_tags: false

skip_non_tags: false

skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/      # Regex for matching commit message

max_jobs: 1

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_folder: c:\projects\pact-php

install:
  - cinst php --version 7.0.27
  - set PATH=C:\tools\php70;%PATH%
  - cmd: copy /Y .\tests\PhpPact\php.ini C:\tools\php70\
  - cmd: php -v
  - cinst docker-compose
  - docker version
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - cmd: php .\composer.phar update

build: off

test_script:
  - cmd: docker-compose up -d
  - cmd: php .\composer.phar test

on_success:
  - echo Success

on_failure:
  - echo Failure